# Generated by Django 3.1.1 on 2020-10-01 06:04

from django.db import migrations, models
import portfolio.models
import portfolio.validators


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_squashed_0012_auto_20200922_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoller',
            name='profile_picture',
            field=models.ImageField(default='generic_user.png', upload_to=portfolio.models.profile_picture_path, validators=[portfolio.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='projectimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.models.project_images_path, validators=[portfolio.validators.validate_file_size]),
        ),
    ]
