# Generated by Django 3.1.1 on 2020-09-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200911_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoller',
            name='contact_number',
            field=models.IntegerField(default=None, null=True, unique=True),
        ),
    ]
