# Generated by Django 3.1.1 on 2020-09-14 04:25

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200911_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoller',
            name='contact_number',
        ),
        migrations.AddField(
            model_name='portfoller',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, null=True, region=None, unique=True),
        ),
    ]
