# Generated by Django 3.1.1 on 2020-09-16 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_portfoller_biography'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('project_name', 'user')},
        ),
    ]
