# Generated by Django 3.1.1 on 2020-09-22 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20200922_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
